### ISSUE TITLE
Berlin network crash

### ISSUE THREAD

**Issue by robcxyz** [icon-project/goloop#126]
I just had all of my berlin nodes crash. I understand that this was because of the reset but I am not sure how to recover properly. I restarted nodes and they aren't producing new blocks. I wiped a DB and it came back tot he same BH even though the foundation tracker is showing a BH in the [144,428](https://berlin.tracker.solidwallet.io/block/144428) range. 

Do I need to set a new mig endpoint or something to recover properly? Also to be clear, all the contracts are lost and need to be redeployed correct? So I should also wipe all my indexes as well?

This was the last log but I don't think it matters considering the above....

```text
berlin_1         |  7 Nov 02:51:56 ntpdate[2116]: adjust time server 17.253.52.253 offset -0.000021 sec
berlin_1         |  7 Nov 05:52:03 ntpdate[2121]: adjust time server 17.253.52.253 offset +0.000026 sec
berlin_1         | Task exception was never retrieved
berlin_1         | future: <Task finished coro=<NodeChecker.check_node() done, defined at /ctx/manager/node_checker.py:62> exception=SystemExit(127)>
berlin_1         | Traceback (most recent call last):
berlin_1         |   File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
berlin_1         |     return loop.run_until_complete(main)
berlin_1         |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 574, in run_until_complete
berlin_1         |     self.run_forever()
berlin_1         |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
berlin_1         |     self._run_once()
berlin_1         |   File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
berlin_1         |     handle._run()
berlin_1         |   File "/usr/local/lib/python3.7/asyncio/events.py", line 88, in _run
berlin_1         |     self._context.run(self._callback, *self._args)
berlin_1         |   File "/ctx/manager/node_checker.py", line 134, in check_node
berlin_1         |     sys.exit(127)
berlin_1         | SystemExit: 127
task ${TASK_NAME} exiting with exit code 127
berlin_1         | task ${TASK_NAME} exiting with exit code 256
berlin_1         | [cont-finish.d] executing container finish scripts...
berlin_1         | [cont-finish.d] graceful_shutdown: executing... 
berlin_1         | s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
berlin_1         | [cont-finish.d] graceful_shutdown: exited 100.
berlin_1         | [cont-finish.d] done.
berlin_1         | [s6-finish] waiting for services.
berlin_1         | [s6-finish] sending all processes the TERM signal.
berlin_1         | [s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by dhgwak** [comment]
Synchronization is possible from BH 0 now. 
The network was initialized and the internal configuration information was changed. 
Therefore, synchronization with the **existing DB** will not be possible.
New DB was uploaded, so you can synchronize from BH 0 or download DB(FASTEST_START='true').

**Comment by robcxyz** [comment]
Fixed and forgot to close this
