### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by godloveBiya** [icon-project/goloop#209]
```
P|20241210-13:54:10.676612|----|-|metric|metric.go:101 Fail tag.New invalid value: only ASCII characters accepted; max length must be 255 characters

```

**Comment by godlovericea** [comment]
when i  run 
```
go mod tidy
```

it panic with error:
```
Starting: C:\Users\Administrator\go\bin\dlv.exe dap --listen=127.0.0.1:61615 from d:\kerying_all\dev_keyring_gitee\kerying_dot
DAP server listening at: 127.0.0.1:61615
Type 'dlv help' for list of commands.
P|20241210-13:46:33.439629|----|-|metric|metric.go:101 Fail tag.New invalid value: only ASCII characters accepted; max length must be 255 characters
panic: (*logrus.Entry) 0xc0007c3b20

goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0007c3ab0, 0x0, {0xc0000b43c0, 0x5d})
	C:/Users/Administrator/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x395
github.com/sirupsen/logrus.(*Entry).Log(0xc0007c3ab0, 0x0, {0xc0007658e8, 0x1, 0x1})
	C:/Users/Administrator/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x88
github.com/sirupsen/logrus.(*Entry).Logf(0xc0007c3ab0, 0x0, {0x42510e6, 0x10}, {0xc0007ba1e0, 0x1, 0x1})
	C:/Users/Administrator/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x145
github.com/sirupsen/logrus.(*Logger).Logf(0xc0003d3900, 0x0, {0x42510e6, 0x10}, {0xc0007ba1e0, 0x1, 0x1})
	C:/Users/Administrator/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:154 +0x89
github.com/sirupsen/logrus.(*Logger).Panicf(0xc0003d3900, {0x42510e6, 0x10}, {0xc0007ba1e0, 0x1, 0x1})
	C:/Users/Administrator/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:195 +0x4c
github.com/icon-project/goloop/server/metric.GetMetricContext({0x46a8850, 0x534f220}, 0x52bc6b0, {0xc0007b07f0, 0x6})
	C:/Users/Administrator/go/pkg/mod/github.com/icon-project/goloop@v1.4.4/server/metric/metric.go:101 +0x54a
github.com/icon-project/goloop/server/metric.init()
	C:/Users/Administrator/go/pkg/mod/github.com/icon-project/goloop@v1.4.4/server/metric/metric.go:30 +0x1725
Process 23652 has exited with status 2
Detaching

```

**Comment by godlovericea** [comment]
my go version is  1.23.2
```
P|20241210-14:17:37.749472|----|-|metric|metric.go:101 Fail tag.New invalid value: only ASCII characters accepted; max length must be 255 characters

```

![image](https://github.com/user-attachments/assets/ccad0a62-b0b3-43e6-94f3-3ad57dc744ce)
