### ISSUE TITLE
Segmentation Fault using Gochain

### ISSUE THREAD

**Issue by jorisvial** [icon-project/goloop#62]
Hi,

I used the following command to build gochain image `GL_TAG=0.9.7 make gochain-icon-image`. When I run the the container using `docker-compose up -d`, gochain crashes with a `SIGSEGV: segmentation violation`.

I'm using `master` branch, and I'm commit `7ed77249c2b4f3fd0c062f8cbfce8879f08bc09c`.

Here is the full log.

```
Attaching to gochain_gochain_1
gochain_1  | I|20210730-02:45:00.450058|b6b5|-|main|main.go:431   ____  ___   ____ _   _    _    ___ _   _ 

gochain_1  | I|20210730-02:45:00.450421|b6b5|-|main|main.go:431  / ___|/ _ \ / ___| | | |  / \  |_ _| \ | |
gochain_1  | I|20210730-02:45:00.450437|b6b5|-|main|main.go:431 | |  _| | | | |   | |_| | / _ \  | ||  \| |
gochain_1  | I|20210730-02:45:00.450481|b6b5|-|main|main.go:431 | |_| | |_| | |___|  _  |/ ___ \ | || |\  |
gochain_1  | I|20210730-02:45:00.450489|b6b5|-|main|main.go:431  \____|\___/ \____|_| |_/_/   \_\___|_| \_|
gochain_1  | I|20210730-02:45:00.450496|b6b5|-|main|main.go:433 Version : v0.9.9-128-g7ed77249-dirty
gochain_1  | I|20210730-02:45:00.450536|b6b5|-|main|main.go:434 Build   : linux/amd64 tags()-2021-07-30-02:36:56
gochain_1  | I|20210730-02:45:00.450549|b6b5|-|metric|metric.go:150 Initialize rootMetricCtx
gochain_1  | T|20210730-02:45:00.450980|b6b5|-|TP|transport.go:383 registerPeerHandler &{0xc0001e6780 0xc0001e6720 map[] {{0 0} 0 0 0 0} 0xc0001e67e0} true
gochain_1  | T|20210730-02:45:00.451003|b6b5|-|TP|transport.go:383 registerPeerHandler &{0xc0001e66f0 :8080} true
gochain_1  | T|20210730-02:45:00.451017|b6b5|-|TP|transport.go:383 registerPeerHandler &{0xc0001e6600 0xc000062000 map[] map[] 2 {{0 0} 0 0 0 0} {0 0}} true
gochain_1  | I|20210730-02:45:00.451406|b6b5|-|eeproxy|enginefactory.go:9 Allocate Engines:[python java]
gochain_1  | D|20210730-02:45:00.451735|b6b5|-|javaee|javaee.go:84 JavaEE Init net(unix), addr(/tmp/socket)
gochain_1  | D|20210730-02:45:00.452399|b6b5|-|javaee|javaee.go:66 start JavaEE addr(/tmp/socket), PID(18), state(0x0), 
gochain_1  | I|20210730-02:45:00.452738|b6b5|-|pyee|pyee.go:172 start instance uid=fb49b66a-5b74-4d91-abc0-1844767a1446
gochain_1  | I|20210730-02:45:00.454271|b6b5|-|chain|chain.go:402 ConfigFilepath /testsuite/config/icon.json BaseDir ../data/iconee ChainDir /testsuite/data/iconee
gochain_1  | I|20210730-02:45:00.454453|b6b5|d65248|chain|chain.go:338 prepare a directory /testsuite/data/iconee/db for database
gochain_1  | I|20210730-02:45:00.495544|b6b5|d65248|chain|chain.go:329 STARTING Consensus
gochain_1  | I|20210730-02:45:00.495588|b6b5|d65248|NM|network.go:41 NetworkManager use channel=d65248 for cid=0xd65248 nid=0x3
gochain_1  | D|20210730-02:45:00.495752|b6b5|d65248|NM|network.go:66 NewManager d65248
gochain_1  | D|20210730-02:45:00.500496|b6b5|d65248|statesync|manager.go:122 NewSyncManager
gochain_1  | D|20210730-02:45:00.500681|b6b5|d65248|BM|manager.go:600 NewBlockManager
gochain_1  | D|20210730-02:45:00.500774|b6b5|d65248|BM|manager.go:967 FinalizeGenesisBlock()
gochain_1  | D|20210730-02:45:00.501107|b6b5|d65248|SV|transition.go:397 reportValidation(err=<nil>)
gochain_1  | D|20210730-02:45:00.501644|b6b5|d65248|SV|transition.go:530 Transition.doExecute: height=0 csi=ConsensusInfo(proposer=<nil>,voters=<nil>,voted=[])
gochain_1  | T|20210730-02:45:00.501671|b6b5|d65248|SV|transition_se.go:37 START TX <0xd652483a5afddd8c9d98a0d81c383f90c8f12c987e8b4869e0abac5b17b707dd>
gochain_1  | D|20210730-02:45:00.501915|b6b5|d65248|ICON|chainscore.go:892 add validator 0: hxb6b5791be0b5ef67063b3c10b840fb81514db2fd
gochain_1  | I|20210730-02:45:00.502141|b6b5|d65248|ICON|chainscore.go:780 Failed to open configuration file open ./icon_config.json: no such file or directory. Use default config
gochain_1  | I|20210730-02:45:00.502255|b6b5|d65248|SV|chainscore_basic.go:134 IconConfig: termPeriod=43200 mainPReps=22 subPReps=78 irep=0 rrep=1200 br=5 upMultiplier=7 unstakeSlotMax=1000 unboudingMax=100 vpCond=660 cvpCond=5 cvpMask=30 cvpsRatio=10 Iglobal=15552000000 Iprep=50 Icps=0 Irelay=0 Ivoter=50
gochain_1  | panic: runtime error: invalid memory address or nil pointer dereference
gochain_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x10dc198]
gochain_1  | 
gochain_1  | goroutine 45 [running]:
gochain_1  | github.com/icon-project/goloop/icon.(*chainScore).handleRevisionChange(0xc0004b8aa0, 0x15debe0, 0xc00015a500, 0x1, 0xd, 0xc00021e930, 0x0)
gochain_1  | 	/work/icon/chainscore_basic.go:245 +0x598
gochain_1  | github.com/icon-project/goloop/icon.(*chainScore).Install(0xc0004b8aa0, 0xc0004bc1e0, 0x1db, 0x1e0, 0xc000157380, 0x0)
gochain_1  | 	/work/icon/chainscore.go:946 +0xd90
gochain_1  | github.com/icon-project/goloop/service/contract.DeployAndInstallSystemSCORE(0x15e4980, 0xc000157380, 0x142a3ee, 0xe, 0x0, 0x0, 0x15c8f60, 0xc0000343c0, 0xc0004bc1e0, 0x1db, ...)
gochain_1  | 	/work/service/contract/contractmanager.go:95 +0x2a8
gochain_1  | github.com/icon-project/goloop/service/transaction.(*genesisV3).Execute(0xc0004fcbd0, 0x15e12a0, 0xc0004fe2a0, 0x0, 0x0, 0x0, 0x0, 0x0)
gochain_1  | 	/work/service/transaction/genesis_v3.go:260 +0x7d0
gochain_1  | github.com/icon-project/goloop/service.(*transition).executeTxsSequential(0xc000033cc0, 0x15c9260, 0xc00017f780, 0x15e12a0, 0xc0004fe2a0, 0xc00017fd30, 0x1, 0x1, 0x13a9540, 0x1)
gochain_1  | 	/work/service/transition_se.go:54 +0x757
gochain_1  | github.com/icon-project/goloop/service.(*transition).executeTxs(0xc000033cc0, 0x15c9260, 0xc00017f780, 0x15e12a0, 0xc0004fe2a0, 0xc00017fd30, 0x1, 0x1, 0x0, 0x0)
gochain_1  | 	/work/service/transition.go:645 +0x16a
gochain_1  | github.com/icon-project/goloop/service.(*transition).doExecute(0xc000033cc0, 0xc00017f700)
gochain_1  | 	/work/service/transition.go:542 +0x6ce
gochain_1  | created by github.com/icon-project/goloop/service.(*transition).startExecution
gochain_1  | 	/work/service/transition.go:290 +0x198
gochain_gochain_1 exited with code 0
```

**Comment by jorisvial** [comment]
Also reproduced the same crash with `GL_TAG=0.9.9`

**Comment by jorisvial** [comment]
Fixed in https://github.com/icon-project/goloop/commit/a006424084c3e31ba0be7438ce8aa2e954d87731
