### ISSUE TITLE
int implicitely converted to BigInteger in interscore call

### ISSUE THREAD

**Issue by ICONationDevTeam** [icon-project/goloop#65]
For unknown reason, an `int` return type from a foreign SCORE is converted to `BigInteger` through an interscore call.

Repro code: 

```java
package com.iconloop.score.example;

import score.Address;
import score.Context;

public class HelloWorld {
    private final int decimals;

    public HelloWorld() {
        // cx2597d4374478674f94e69599301e5f31146bd71d is the address of a standard IRC2 Java contract
        Address target = Address.fromString("cx2597d4374478674f94e69599301e5f31146bd71d");
        this.decimals = (int) Context.call(target, "decimals");
    }
}
```

The relevant error during deployment (that error also happens after deployment by calling any method)

```log
DApp deployment failed: java.lang.ClassCastException: class s.java.math.BigInteger cannot be cast to class 
s.java.lang.Integer (s.java.math.BigInteger and s.java.lang.Integer are in unnamed module of loader 'app')
```

The entire iconee.log when deploying to localnet: 

```log
callhandler.go:281 Execution INVOKE last=0 eid=1
proxy.go:235 Proxy[0xc0004d8c80].Invoke code=/testsuite/chain/iconee/contract/0xb0099b3a6ce34422125c32572671bd007272ebd23e445800ef4b3952f198b35d query=false from=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd to=cx735e2a5e0088ef43ba8e4ee45fcf7b3b788422cf value=0 limit=1473895800 method=<init> eid=1
log.go:205  [INVOKE]
log.go:205  >>> code=/testsuite/chain/iconee/contract/0xb0099b3a6ce34422125c32572671bd007272ebd23e445800ef4b3952f198b35d
log.go:205      isQuery=false
log.go:205      from=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd
log.go:205        to=cx735e2a5e0088ef43ba8e4ee45fcf7b3b788422cf
log.go:205      value=0
log.go:205      limit=1473895800
log.go:205      method=<init>
log.go:205      params=[
log.go:205      ]
log.go:205  >>> getInfo: info={B.height=294, B.timestamp=1631009433329336, C.owner=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd, Revision=277517, StepCosts={apiCall=10000, contractCall=25000, contractCreate=1000000000, contractDestruct=-70000, contractSet=30000, contractUpdate=1600000000, default=100000, delete=-240, eventLog=100, input=200, replace=80, set=320}, T.from=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd, T.hash=[B@25ef0adf, T.index=0, T.nonce=0, T.timestamp=1631009433325000}
log.go:205      txHash=33f68fb76b78a6b456e91d4deeebb027b87689f0177faecbf6397f8c83dc959a
log.go:205      txIndex=0
log.go:205      txFrom=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd
log.go:205      txTimestamp=1631009433325000
log.go:205      txNonce=0
log.go:205      blockHeight=294
log.go:205      blockTimestamp=1631009433329336
log.go:205      contractOwner=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd
log.go:205      stepCosts={apiCall=10000, contractCall=25000, contractCreate=1000000000, contractDestruct=-70000, contractSet=30000, contractUpdate=1600000000, default=100000, delete=-240, eventLog=100, input=200, replace=80, set=320}
log.go:205  === DAppCreator ===
log.go:205  [getCode]
log.go:205  [getBlockTimestamp] ret=1631009433329336
log.go:205  [setTransformedCode] len=1225
log.go:205  [call] target=cx2597d4374478674f94e69599301e5f31146bd71d value=0 limit=1473894603 dataType=call dataObj={method=decimals, params=[Ljava.lang.Object;@44e204e2} 
proxy.go:432 Proxy[0xc0004d8c80].OnCall from=cx735e2a5e0088ef43ba8e4ee45fcf7b3b788422cf to=cx2597d4374478674f94e69599301e5f31146bd71d value=0 limit=1473894603 type=call data=&{{1 0xc0020d0840}}
callhandler.go:281 Execution INVOKE last=0 eid=2
proxy.go:235 Proxy[0xc0004d8c80].Invoke code=/testsuite/chain/iconee/contract/0x4dfb32b69817cf7281718d9db817d220cabd6c03eb6b26a82f1ca954dd037e75 query=true from=cx735e2a5e0088ef43ba8e4ee45fcf7b3b788422cf to=cx2597d4374478674f94e69599301e5f31146bd71d value=0 limit=1473869603 method=decimals eid=2
log.go:205  [INVOKE]
log.go:205  >>> code=/testsuite/chain/iconee/contract/0x4dfb32b69817cf7281718d9db817d220cabd6c03eb6b26a82f1ca954dd037e75
log.go:205      isQuery=true
log.go:205      from=cx735e2a5e0088ef43ba8e4ee45fcf7b3b788422cf
log.go:205        to=cx2597d4374478674f94e69599301e5f31146bd71d
log.go:205      value=0
log.go:205      limit=1473869603
log.go:205      method=decimals
log.go:205      params=[
log.go:205      ]
log.go:205  >>> getInfo: info={B.height=294, B.timestamp=1631009433329336, C.owner=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd, Revision=277517, StepCosts={apiCall=10000, contractCall=25000, contractCreate=1000000000, contractDestruct=-70000, contractSet=30000, contractUpdate=1600000000, default=100000, delete=-240, eventLog=100, input=200, replace=80, set=320}, T.from=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd, T.hash=[B@6d16a8b1, T.index=0, T.nonce=0, T.timestamp=1631009433325000}
log.go:205      txHash=33f68fb76b78a6b456e91d4deeebb027b87689f0177faecbf6397f8c83dc959a
log.go:205      txIndex=0
log.go:205      txFrom=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd
log.go:205      txTimestamp=1631009433325000
log.go:205      txNonce=0
log.go:205      blockHeight=294
log.go:205      blockTimestamp=1631009433329336
log.go:205      contractOwner=hxb6b5791be0b5ef67063b3c10b840fb81514db2fd
log.go:205      stepCosts={apiCall=10000, contractCall=25000, contractCreate=1000000000, contractDestruct=-70000, contractSet=30000, contractUpdate=1600000000, default=100000, delete=-240, eventLog=100, input=200, replace=80, set=320}
proxy.go:359 Proxy[0xc0004d8c80].OnResult status=Success steps=34
callhandler.go:398 Execution RESULT last=1 eid=3
proxy.go:300 Proxy[0xc0004d8c80].SendResult status=<nil> steps=25034 last=1 eid=3
log.go:205  [RESULT]
log.go:205  [call] result=Result{status=0, stepUsed=25034, ret=18, eid=3, prevEID=1}
log.go:205  DApp deployment failed: java.lang.ClassCastException: class s.java.math.BigInteger cannot be cast to class s.java.lang.Integer (s.java.math.BigInteger and s.java.lang.Integer are in unnamed module of loader 'app')
i.UncaughtException: java.lang.ClassCastException: class s.java.math.BigInteger cannot be cast to class s.java.lang.Integer (s.java.math.BigInteger and s.java.lang.Integer are in unnamed module of loader 'app')
	at org.aion.avm.core.persistence.LoadedDApp.handleUncaughtException(LoadedDApp.java:355)
	at org.aion.avm.core.persistence.LoadedDApp.initMainInstance(LoadedDApp.java:287)
	at org.aion.avm.core.DAppCreator.runClinitAndCreateMainInstance(DAppCreator.java:118)
	at org.aion.avm.core.DAppCreator.create(DAppCreator.java:70)
	at foundation.icon.ee.score.AvmExecutor.runCommon(AvmExecutor.java:99)
	at foundation.icon.ee.score.AvmExecutor.runExternal(AvmExecutor.java:74)
	at foundation.icon.ee.score.AvmExecutor.run(AvmExecutor.java:61)
	at foundation.icon.ee.score.TransactionExecutor.handleInvoke(TransactionExecutor.java:155)
	at foundation.icon.ee.ipc.EEProxy.handleInvoke(EEProxy.java:311)
	at foundation.icon.ee.ipc.EEProxy.doHandleMessages(EEProxy.java:123)
	at foundation.icon.ee.ipc.EEProxy.handleMessages(EEProxy.java:109)
	at foundation.icon.ee.score.TransactionExecutor.connectAndRunLoop(TransactionExecutor.java:104)
	at foundation.icon.ee.score.TransactionExecutor.connectAndRunLoop(TransactionExecutor.java:96)
	at foundation.icon.ee.ipc.ExecutorManager.lambda$runExecutor$0(ExecutorManager.java:73)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassCastException: class s.java.math.BigInteger cannot be cast to class s.java.lang.Integer (s.java.math.BigInteger and s.java.lang.Integer are in unnamed module of loader 'app')
	at u.A.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.aion.avm.core.persistence.LoadedDApp.initMainInstance(LoadedDApp.java:284)
	... 13 more
log.go:205  Result{status=1, stepUsed=26831, ret=UnknownFailure, eid=0, prevEID=0}
proxy.go:359 Proxy[0xc0004d8c80].OnResult status=UnknownFailure steps=26831

```

The "decimals" method definition in the standard IRC2 contract is the following : 

```java
@External(readonly=true)
public int decimals() {
    return decimals;
}
```

Is that the intended behavior ?

**Comment by hijung-icon** [comment]
Yes. It is intented behavior.

**Comment by ICONationDevTeam** [comment]
Thanks for the clarification!
