### ISSUE TITLE
`getPreps` in System Score in gochain-local doesn't take parameters

### ISSUE THREAD

**Issue by nightowl121** [icon-project/goloop#94]
According to api specification `getPreps` method takes start ranking and end ranking parameters.
https://github.com/icon-project/goloop/blob/master/doc/iiss_extension.md#getpreps. Although, in gochain-local supplying parameters for `getPreps` method gives illegal argument exception.

```
T|20220322-09:19:12.621368|b6b5|3325fd|SV|2d6aed0b|log.go:205 java|cxbb63b132|foundation.icon.ee.score.ExternalState [call] target=cx0000000000000000000000000000000000000000 value=0 limit=783739547 dataType=call dataObj={params=[Ljava.lang.Object;@6c1ed24a, method=getPReps} 
T|20220322-09:19:12.621532|b6b5|3325fd|SV|2d6aed0b|proxy.go:466 Proxy[0xc0004c5f00].OnCall from=cxbb63b132573d9fb2226ce5158bbaf174b964e46c to=cx0000000000000000000000000000000000000000 value=0 limit=783739547 type=call data=&{{1 0xc0019dc240}}
T|20220322-09:19:12.622900|b6b5|3325fd|SV|callhandler.go:394 Execution RESULT last=2 eid=3
T|20220322-09:19:12.623032|b6b5|3325fd|SV|2d6aed0b|proxy.go:334 Proxy[0xc0004c5f00].SendResult status=E0006:Failed to get PReps: start=1 end=100 steps=25000 last=2 eid=3
T|20220322-09:19:12.623679|b6b5|3325fd|SV|2d6aed0b|log.go:205 java|cxbb63b132|foundation.icon.ee.ipc.EEProxy [RESULT]
T|20220322-09:19:12.623782|b6b5|3325fd|SV|2d6aed0b|log.go:205 java|cxbb63b132|foundation.icon.ee.score.ExternalState [call] result=Result{status=6, stepUsed=25000, ret=Failed to get PReps: start=1 end=100, eid=3, prevEID=2}
T|20220322-09:19:12.624509|b6b5|3325fd|SV|2d6aed0b|log.go:205 java|cxbb63b132|org.aion.avm.core.DAppCreator DApp deployment failed: java.lang.IllegalArgumentException: InvalidParameter
D|20220322-09:19:12.625495|b6b5|-|javaee|i.UncaughtException: java.lang.IllegalArgumentException: InvalidParameter
D|20220322-09:19:12.626568|b6b5|-|javaee|	at org.aion.avm.core.persistence.LoadedDApp.handleUncaughtException(LoadedDApp.java:360)
D|20220322-09:19:12.626619|b6b5|-|javaee|	at org.aion.avm.core.persistence.LoadedDApp.initMainInstance(LoadedDApp.java:290)
D|20220322-09:19:12.626649|b6b5|-|javaee|	at org.aion.avm.core.DAppCreator.runClinitAndCreateMainInstance(DAppCreator.java:124)
D|20220322-09:19:12.626700|b6b5|-|javaee|	at org.aion.avm.core.DAppCreator.create(DAppCreator.java:73)
D|20220322-09:19:12.627043|b6b5|-|javaee|	at foundation.icon.ee.score.AvmExecutor.runCommon(AvmExecutor.java:99)
D|20220322-09:19:12.627086|b6b5|-|javaee|	at foundation.icon.ee.score.AvmExecutor.runExternal(AvmExecutor.java:74)
D|20220322-09:19:12.627115|b6b5|-|javaee|	at foundation.icon.ee.score.AvmExecutor.run(AvmExecutor.java:61)
D|20220322-09:19:12.627373|b6b5|-|javaee|	at foundation.icon.ee.score.TransactionExecutor.handleInvoke(TransactionExecutor.java:145)
```

If no parameters are provided the call works.

```
T|20220322-08:59:22.730005|b6b5|3325fd|SV|2d6aed0b|log.go:205 java|cx1a880a2b|foundation.icon.ee.score.ExternalState [call] target=cx0000000000000000000000000000000000000000 value=0 limit=784047639 dataType=call dataObj={params=[Ljava.lang.Object;@3eb6e668, method=getPReps} 
T|20220322-08:59:22.730104|b6b5|3325fd|SV|2d6aed0b|proxy.go:466 Proxy[0xc0004c5f00].OnCall from=cx1a880a2b89dbd8851275db74000f4f57ce272ec9 to=cx0000000000000000000000000000000000000000 value=0 limit=784047639 type=call data=&{{1 0xc00007f8c0}}
T|20220322-08:59:22.731273|b6b5|3325fd|SV|callhandler.go:394 Execution RESULT last=2 eid=3
T|20220322-08:59:22.731308|b6b5|3325fd|SV|2d6aed0b|proxy.go:334 Proxy[0xc0004c5f00].SendResult status=<nil> steps=25000 last=2 eid=3
T|20220322-08:59:22.731646|b6b5|3325fd|SV|2d6aed0b|log.go:205 java|cx1a880a2b|foundation.icon.ee.ipc.EEProxy [RESULT]
T|20220322-08:59:22.731960|b6b5|3325fd|SV|2d6aed0b|log.go:205 java|cx1a880a2b|foundation.icon.ee.score.ExternalState [call] result=Result{status=0, stepUsed=25000, ret={blockHeight=125, preps=[Ljava.lang.Object;@15dbc64a, startRanking=1, totalDelegated=0, totalStake=0}, eid=3, prevEID=2}
```

There is difference in behavior in working of `getPreps` method than the specification.

**Comment by nightowl121** [comment]
https://github.com/icon-project/goloop/blob/master/icon/icsim/simulatorimpl.go#L499
```go
func (sim *simulatorImpl) GetPReps() map[string]interface{} {
	es := sim.getExtensionState(true)
	jso, _ := es.State.GetPRepsInJSON(sim.BlockHeight(), 0, 0)
	return jso
}
```

**Comment by eunsoo-icon** [comment]
Do you have any registered P-Rep?

If first parameter `startRanking` is greater than the P-Rep count, `getPReps` will be failed.

**Comment by sink772** [comment]
Also if your issue is related to `gochain-local`, this repo is not right place to inquiry.  Please use [gochain-local](https://github.com/icon-project/gochain-local) repo hereafter.
